import type { ToolCategory } from '@/types/tools';

export interface ToolComponentBinding {
  category: ToolCategory;
  exportName: string;
}

/**
 * Maps every slug in the tools registry to the component that renders it.
 * The module a component lives in is described by CATEGORY_MODULES, which is
 * loaded on demand so a tool page only ships its own category of tools.
 */
export const TOOL_COMPONENT_BINDINGS: Record<string, ToolComponentBinding> = {
  'age-calculator': { category: 'calculators', exportName: 'AgeCalculatorTool' },
  'area-converter': { category: 'converters', exportName: 'AreaConverterTool' },
  'barcode-generator': { category: 'generators', exportName: 'BarcodeGeneratorTool' },
  'base64-encode-decode': { category: 'developer', exportName: 'Base64Tool' },
  'binary-hex-converter': { category: 'converters', exportName: 'BinaryHexConverterTool' },
  'bmi-calculator': { category: 'calculators', exportName: 'BmiCalculatorTool' },
  'border-radius-generator': { category: 'developer', exportName: 'BorderRadiusTool' },
  'box-shadow-generator': { category: 'developer', exportName: 'BoxShadowTool' },
  'caption-hashtag-generator': { category: 'ai', exportName: 'CaptionHashtagTool' },
  'case-converter': { category: 'text', exportName: 'CaseConverterTool' },
  'channel-name-generator': { category: 'creator', exportName: 'ChannelNameGeneratorTool' },
  'character-counter': { category: 'text', exportName: 'CharacterCounterTool' },
  'color-converter': { category: 'developer', exportName: 'ColorConverterTool' },
  'color-picker': { category: 'images', exportName: 'ColorPickerTool' },
  'compound-interest-calculator': { category: 'calculators', exportName: 'LoanEmiCalculatorTool' },
  'compress-to-size': { category: 'images', exportName: 'CompressToSizeTool' },
  'cooking-units-converter': { category: 'converters', exportName: 'CookingUnitsTool' },
  'cover-letter-generator': { category: 'generators', exportName: 'CoverLetterGeneratorTool' },
  'cron-helper': { category: 'developer', exportName: 'CronHelperTool' },
  'css-gradient-generator': { category: 'developer', exportName: 'CssGradientTool' },
  'csv-to-json': { category: 'developer', exportName: 'CsvToJsonTool' },
  'currency-converter': { category: 'calculators', exportName: 'CurrencyConverterTool' },
  'data-size-converter': { category: 'converters', exportName: 'DataSizeConverterTool' },
  'date-difference-calculator': { category: 'calculators', exportName: 'DateDifferenceTool' },
  'days-until-a-date': { category: 'calculators', exportName: 'DaysUntilDateTool' },
  'diff-checker': { category: 'text', exportName: 'TextDiffTool' },
  'discount-calculator': { category: 'calculators', exportName: 'DiscountCalculatorTool' },
  'email-writer': { category: 'ai', exportName: 'EmailWriterTool' },
  'extract-pdf-pages': { category: 'pdf', exportName: 'ExtractPdfPagesTool' },
  'fancy-text-generator': { category: 'text', exportName: 'FancyTextGeneratorTool' },
  'favicon-generator': { category: 'images', exportName: 'FaviconGeneratorTool' },
  'find-replace': { category: 'text', exportName: 'FindReplaceTool' },
  'fuel-cost-calculator': { category: 'calculators', exportName: 'LoanEmiCalculatorTool' },
  'gold-value-calculator': { category: 'calculators', exportName: 'GoldValueTool' },
  'gpa-calculator': { category: 'calculators', exportName: 'GpaCalculatorTool' },
  'grammar-checker': { category: 'ai', exportName: 'GrammarCheckerTool' },
  'hash-generator': { category: 'developer', exportName: 'HashGeneratorTool' },
  'hourly-to-annual-salary': { category: 'calculators', exportName: 'PakistanIncomeTaxTool' },
  'html-to-text': { category: 'text', exportName: 'HtmlToTextTool' },
  'image-compressor': { category: 'images', exportName: 'ImageCompressorTool' },
  'image-converter': { category: 'images', exportName: 'ImageConverterTool' },
  'image-cropper': { category: 'images', exportName: 'ImageCropperTool' },
  'image-resizer': { category: 'images', exportName: 'ImageResizerTool' },
  'image-to-base64': { category: 'images', exportName: 'ImageToBase64Tool' },
  'images-to-pdf': { category: 'pdf', exportName: 'ImagesToPdfTool' },
  'invoice-generator': { category: 'generators', exportName: 'InvoiceGeneratorTool' },
  'islamic-date-converter': { category: 'generators', exportName: 'IslamicDateConverterTool' },
  'json-formatter': { category: 'developer', exportName: 'JsonFormatterTool' },
  'json-to-csv': { category: 'developer', exportName: 'JsonToCsvTool' },
  'jwt-decoder': { category: 'developer', exportName: 'JwtDecoderTool' },
  'length-converter': { category: 'converters', exportName: 'LengthConverterTool' },
  'loan-emi-calculator': { category: 'calculators', exportName: 'LoanEmiCalculatorTool' },
  'lorem-ipsum': { category: 'text', exportName: 'LoremIpsumTool' },
  'markdown-to-html': { category: 'text', exportName: 'MarkdownToHtmlTool' },
  'meme-maker': { category: 'images', exportName: 'MemeMakerTool' },
  'minify-html-css-js': { category: 'developer', exportName: 'MinifyCodeTool' },
  'mortgage-calculator': { category: 'calculators', exportName: 'LoanEmiCalculatorTool' },
  'number-to-words': { category: 'converters', exportName: 'NumberToWordsTool' },
  'pakistan-income-tax': { category: 'calculators', exportName: 'PakistanIncomeTaxTool' },
  'paraphraser': { category: 'ai', exportName: 'ParaphraserTool' },
  'passport-photo-maker': { category: 'images', exportName: 'PassportPhotoMakerTool' },
  'password-generator': { category: 'generators', exportName: 'PasswordGeneratorTool' },
  'pdf-merger': { category: 'pdf', exportName: 'PdfMergerTool' },
  'pdf-page-numbers': { category: 'pdf', exportName: 'PdfPageNumbersTool' },
  'pdf-rotator': { category: 'pdf', exportName: 'PdfRotatorTool' },
  'pdf-splitter': { category: 'pdf', exportName: 'PdfSplitterTool' },
  'pdf-watermark': { category: 'pdf', exportName: 'PdfWatermarkTool' },
  'percentage-calculator': { category: 'calculators', exportName: 'PercentageCalculatorTool' },
  'photo-collage': { category: 'images', exportName: 'PhotoCollageTool' },
  'prayer-times': { category: 'generators', exportName: 'PrayerTimesTool' },
  'product-description-writer': { category: 'ai', exportName: 'ProductDescriptionTool' },
  'profit-margin-calculator': { category: 'calculators', exportName: 'PercentageCalculatorTool' },
  'prompt-helper': { category: 'ai', exportName: 'PromptHelperTool' },
  'qr-code-generator': { category: 'generators', exportName: 'QrCodeGeneratorTool' },
  'random-name-generator': { category: 'generators', exportName: 'RandomNameGeneratorTool' },
  'random-number-generator': { category: 'generators', exportName: 'RandomNumberGeneratorTool' },
  'readability-score': { category: 'text', exportName: 'ReadabilityScoreTool' },
  'receipt-generator': { category: 'generators', exportName: 'ReceiptGeneratorTool' },
  'regex-tester': { category: 'developer', exportName: 'RegexTesterTool' },
  'remove-duplicate-lines': { category: 'text', exportName: 'RemoveDuplicateLinesTool' },
  'resume-builder': { category: 'generators', exportName: 'ResumeBuilderTool' },
  'reverse-text': { category: 'text', exportName: 'ReverseTextTool' },
  'roi-calculator': { category: 'calculators', exportName: 'PercentageCalculatorTool' },
  'roman-numerals': { category: 'converters', exportName: 'RomanNumeralsTool' },
  'rotate-flip': { category: 'images', exportName: 'RotateFlipTool' },
  'salary-after-tax': { category: 'calculators', exportName: 'PakistanIncomeTaxTool' },
  'savings-goal-calculator': { category: 'calculators', exportName: 'LoanEmiCalculatorTool' },
  'signature-generator': { category: 'generators', exportName: 'SignatureGeneratorTool' },
  'sort-lines': { category: 'text', exportName: 'SortLinesTool' },
  'speed-converter': { category: 'converters', exportName: 'SpeedConverterTool' },
  'summarizer': { category: 'ai', exportName: 'SummarizerTool' },
  'svg-to-png': { category: 'images', exportName: 'SvgToPngTool' },
  'temperature-converter': { category: 'converters', exportName: 'TemperatureConverterTool' },
  'text-diff': { category: 'text', exportName: 'TextDiffTool' },
  'text-repeater': { category: 'text', exportName: 'TextRepeaterTool' },
  'text-to-slug': { category: 'text', exportName: 'TextToSlugTool' },
  'text-to-speech': { category: 'text', exportName: 'TextToSpeechTool' },
  'thumbnail-maker': { category: 'generators', exportName: 'ThumbnailMakerTool' },
  'time-converter': { category: 'converters', exportName: 'TimeConverterTool' },
  'timestamp-converter': { category: 'developer', exportName: 'TimestampConverterTool' },
  'tip-calculator': { category: 'calculators', exportName: 'TipCalculatorTool' },
  'url-encode-decode': { category: 'developer', exportName: 'UrlEncodeTool' },
  'username-generator': { category: 'generators', exportName: 'UsernameGeneratorTool' },
  'uuid-generator': { category: 'generators', exportName: 'UuidGeneratorTool' },
  'vat-gst-sales-tax': { category: 'calculators', exportName: 'PercentageCalculatorTool' },
  'watermark-adder': { category: 'images', exportName: 'WatermarkAdderTool' },
  'weight-converter': { category: 'converters', exportName: 'WeightConverterTool' },
  'word-counter': { category: 'text', exportName: 'WordCounterTool' },
  'youtube-earnings-calculator': { category: 'creator', exportName: 'YouTubeEarningsCalculatorTool' },
  'youtube-tag-extractor': { category: 'creator', exportName: 'YouTubeTagExtractorTool' },
  'youtube-thumbnail-downloader': { category: 'creator', exportName: 'YouTubeThumbnailDownloaderTool' },
  'youtube-title-generator': { category: 'ai', exportName: 'YouTubeTitleGeneratorTool' },
  'zakat-calculator': { category: 'calculators', exportName: 'ZakatCalculatorTool' },
};

export const CATEGORY_MODULES: Record<ToolCategory, () => Promise<Record<string, React.ComponentType>>> = {
  text: () => import('./text/TextTools'),
  images: () => import('./images/ImageTools'),
  calculators: () => import('./calculators/CalculatorTools'),
  generators: () => import('./generators/GeneratorTools'),
  developer: () => import('./developer/DeveloperTools'),
  converters: () => import('./converters/ConverterTools'),
  pdf: () => import('./pdf/PdfTools'),
  ai: () => import('./ai/AiTools'),
  creator: () => import('./creator/CreatorTools'),
};

export function getToolBinding(slug: string): ToolComponentBinding | undefined {
  return TOOL_COMPONENT_BINDINGS[slug];
}
